import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "react-hot-toast";

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <Toaster />
          <body
            className={`${quicksand.className} ${quicksand.variable} antialiased`}
          >
            {children}
          </body>
        </ThemeProvider>
    </html>
  );
}
